#!/bin/bash
if [[ -d ~/Neevesha ]]
then
	echo "The folder already exists"
else
	mkdir ~/Neevesha
fi

cd ~/Neevesha
if [[ -d ~Neevesha/Tp3-Crypto_Station/crypto ]];
then
	echo "The folder is already cloned"
else
	git clone https://github.com/Neevesha-dev-pixel/Tp3-Crypto_Station.git
fi

cd ~/Neevesha/Tp3-Crypto_Station/crypto/src
sudo chmod u+x encrypt.sh
sudo chmod u+x decrypt.sh


sudo cp -f ~/Neevesha/Tp3-Crypto_Station/crypto/src/encrypt.service /etc/systemd/system/crypt.service
sudo cp -f ~/Neevesha/Tp3-Crypto_Station/crypto/src/decrypt.service /etc/systemd/system/decrypt.service

sudo systemctl daemon-reload
sudo systemctl enable encrypt.service
sudo systemctl enable decrypt.service
sudo systemctl start encrypt.service
sudo systemctl start decrypt.service

echo "Successfully install the program"
